version: '3.8'

services:
  hackwrwork-messenger:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/chiperwork-messenger
      - /chiperwork-messenger/node_modules
    ports:
      - 5173:5173
